### ISSUE TITLE
support npms.io API as fallback URL

### ISSUE THREAD

**Issue by ritz078** [OlivierCoilland/npm-to-github#3]
https://api-docs.npms.io/

As there's a limit to requests we can make on npm.
Also it will be great if the output is same.

**Comment by OlivierCoilland** [comment]
I never reached any limit on npm. However GitHub's API rate limit is really low (30 requests) and triggers this error:

`API rate limit exceeded for a.b.c.d. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

I'm afraid npms won't help, but I'll have a look to authenticated requests.
